export const EMPLOYEES_LOADED = "Employees/EMPLOYEES_LOADED";
export const ADD_EMPLOYEE = "Employees/ADD_EMPLOYEE";
export const FETCHING_EMPLOYEES = "Employees/FETCHING_EMPLOYEES";
export const FETCHING_EMPLOYEES_ERROR = "Employees/FETCHING_EMPLOYEES_ERROR";